name: Build And Upload eckoWallet Extension Zip

on:
  push:
    tags:
      - v2.*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo "REACT_APP_WALLET_CONNECT_PROJECT_ID=${{ secrets.REACT_APP_WALLET_CONNECT_PROJECT_ID }}" >> .env
          echo "REACT_APP_WALLET_CONNECT_RELAY_URL=${{ secrets.REACT_APP_WALLET_CONNECT_RELAY_URL }}" >> .env
          echo "REACT_APP_SIMPLEX_API_URL_DEV=${{ secrets.REACT_APP_SIMPLEX_API_URL_DEV }}" >> .env
          echo "REACT_APP_SIMPLEX_API_URL_PROD=${{ secrets.REACT_APP_SIMPLEX_API_URL_PROD }}" >> .env
          echo "REACT_APP_SIMPLEX_PUBLIC_KEY_DEV=${{ secrets.REACT_APP_SIMPLEX_PUBLIC_KEY_DEV }}" >> .env
          echo "REACT_APP_SIMPLEX_PUBLIC_KEY_PROD=${{ secrets.REACT_APP_SIMPLEX_PUBLIC_KEY_PROD }}" >> .env
          echo "REACT_APP_KDX_GOV_CHAIN_ID=${{ secrets.REACT_APP_KDX_GOV_CHAIN_ID }}" >> .env
          echo "REACT_APP_ECKO_API_URL_DEV=${{ secrets.REACT_APP_ECKO_API_URL_DEV }}" >> .env
          echo "REACT_APP_ECKO_API_URL_PROD=${{ secrets.REACT_APP_ECKO_API_URL_PROD }}" >> .env
          echo "REACT_APP_ECKO_DEXTOOLS_API_URL=${{ secrets.REACT_APP_ECKO_DEXTOOLS_API_URL }}" >> .env

      - name: Build extension
        run: npm run build

      - name: Zip build with tag
        run: |
          mkdir -p dist-zip
          zip -r dist-zip/build_${GITHUB_REF##*/}.zip ./build

      - name: Upload extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-${{ github.ref_name }}
          path: dist-zip/build_${{ github.ref_name }}.zip
